#!/bin/bash
echo "Killing SnapBack..."
killall SnapBack
wait
echo "Setting SnapBack binary ownership..."
chown 0:0 /Applications/SnapBack.app
chown 0:0 /Applications/SnapBack.app/SnapBack
chmod +s /Applications/SnapBack.app/SnapBack
echo "Refreshing ui cache..."
echo "Your focus determines your reality."
echo "Special Thanks To:"
echo "CreatureSurvive, PINPAL, the_casle,"
echo "pwn20wnd, sbingner, Samg_is_a_Ninja,"
echo "Tony, Chilaxan and Easy-Z"
echo "Without you guys, I would not be here today."
echo "This is a new day, a new beginning."
/usr/bin/uicache -p /Applications/SnapBack.app

